# Generated by Django 5.0.4 on 2024-08-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
    ]
