# Generated by Django 5.0.4 on 2024-08-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
    ]
